### ISSUE TITLE
Leafletjs pinch-zoom animation does not work for Tangram maps

### ISSUE THREAD

**Issue by metalaureate** [tangrams/simple-demo#3]
Not sure where to ask about this... (Awesome tech btw) I am unable to get Leaflet pinch-zoom animations to work on Tangram maps. I wondered if this is a known limitation or a bug?

Your own demos do not exhibit it either, compare leaflet's demo on http://leafletjs.com/.

**Comment by meetar** [comment]
Hi Simon, thanks for the report, this should be working (and currently seems to be working on my iPhone) – what browser/platform are you on?

**Comment by metalaureate** [comment]
Well that's embarrassing -- I cannot reproduce it.
