### ISSUE TITLE
Switch to license without attribution?

### ISSUE THREAD

**Issue by pnorman** [tangrams/simple-demo#6]
As a demo page, it would be useful to be able to include this page in demos which are public domain, or similar projects. Would it be possible to change the license?

Alternatively, the license could be included in the HTML page. Normally this isn't necessary, but there's a high change here of the page and LICENSE file becoming separated.

**Comment by meetar** [comment]
As I understand it the license text doesn't need to be in a separate file, so feel free to move it into the html for any copies you make.
